### ISSUE TITLE
arguments incorrect?

### ISSUE THREAD

**Issue by DownsideupmediaUSA** [learn-co-curriculum/apples-and-holidays#40]
Hi there. 

I was struggling with a lot of this lesson evidently due to the fact that some of the pre-filled arguments for the last few methods in this lab didn't match up to what was provided in the solution. Since I'm fairly new to this I didn't realize that I can just alter those arguments to best fit the solutions needed. I tend to take things too literally so its probably my fault for not realizing I could make those sorts of changes, but it might help some of us newbs if that was mentioned in the hint section.

**Comment by alexgriff** [comment]
Change parameter names in solution branch to match those in stubbed out methods provided to students
